# C++ 高性能微信小程序 AI 对话后端系统配置文件

# 服务器配置
[server]
port = 8080
threads = 0  # 0表示使用硬件核心数

# 数据库配置
[database]
connection_string = "postgresql://ai_service:your_secure_password@localhost/ai_backend"
min_connections = 5
max_connections = 20

# 认证配置
[auth]
jwt_secret = "default_secret_key_change_in_production"
jwt_issuer = "ai_backend"
access_token_lifetime = 3600     # 1小时
refresh_token_lifetime = 2592000 # 30天

# 文件上传配置
[file]
upload_dir = "uploads"
allowed_extensions = [".jpg", ".jpeg", ".png", ".gif", ".pdf", ".txt", ".md", ".csv"]
max_size = 10485760  # 10MB
base_url = "/files"

# 日志配置
[log]
level = "info"
request_level = "info"
request_body = false
request_headers = false

# CORS配置
[cors]
allowed_origins = ["*"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["Content-Type", "Authorization"]
allow_credentials = true
max_age = 86400

# 速率限制配置
[rate_limit]
enabled = true
max_requests_per_minute = 60
max_requests_per_hour = 1000

# AI模型配置
[ai]
default_model = "deepseek-v3"

[ai.wenxin]
api_key = ""
api_secret = ""
base_url = "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat"

[ai.xunfei]
app_id = ""
api_key = ""
api_secret = ""
base_url = "wss://spark-api.xf-yun.com/v2.1/chat"

[ai.tongyi]
api_key = ""
base_url = "https://api.tongyi.aliyun.com/v1"

[ai.deepseek]
api_key = ""
base_url = "https://api.deepseek.com/v1"